// Code generated by protoc-gen-go.
// source: riak_yokozuna.proto
// DO NOT EDIT!

/*
Package riak_yokozuna is a generated protocol buffer package.

It is generated from these files:
	riak_yokozuna.proto

It has these top-level messages:
	RpbYokozunaIndex
	RpbYokozunaIndexGetReq
	RpbYokozunaIndexGetResp
	RpbYokozunaIndexPutReq
	RpbYokozunaIndexDeleteReq
	RpbYokozunaSchema
	RpbYokozunaSchemaPutReq
	RpbYokozunaSchemaGetReq
	RpbYokozunaSchemaGetResp
*/
package riak_yokozuna

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpbYokozunaIndex struct {
	Name             []byte  `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Schema           []byte  `protobuf:"bytes,2,opt,name=schema" json:"schema,omitempty"`
	NVal             *uint32 `protobuf:"varint,3,opt,name=n_val,json=nVal" json:"n_val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpbYokozunaIndex) Reset()                    { *m = RpbYokozunaIndex{} }
func (m *RpbYokozunaIndex) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndex) ProtoMessage()               {}
func (*RpbYokozunaIndex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpbYokozunaIndex) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RpbYokozunaIndex) GetSchema() []byte {
	if m != nil {
		return m.Schema
	}
	return nil
}

func (m *RpbYokozunaIndex) GetNVal() uint32 {
	if m != nil && m.NVal != nil {
		return *m.NVal
	}
	return 0
}

// GET request - If a name is given, return matching index, else return all
type RpbYokozunaIndexGetReq struct {
	Name             []byte `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaIndexGetReq) Reset()                    { *m = RpbYokozunaIndexGetReq{} }
func (m *RpbYokozunaIndexGetReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexGetReq) ProtoMessage()               {}
func (*RpbYokozunaIndexGetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpbYokozunaIndexGetReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaIndexGetResp struct {
	Index            []*RpbYokozunaIndex `protobuf:"bytes,1,rep,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *RpbYokozunaIndexGetResp) Reset()                    { *m = RpbYokozunaIndexGetResp{} }
func (m *RpbYokozunaIndexGetResp) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexGetResp) ProtoMessage()               {}
func (*RpbYokozunaIndexGetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpbYokozunaIndexGetResp) GetIndex() []*RpbYokozunaIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

// PUT request - Create a new index
type RpbYokozunaIndexPutReq struct {
	Index            *RpbYokozunaIndex `protobuf:"bytes,1,req,name=index" json:"index,omitempty"`
	Timeout          *uint32           `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *RpbYokozunaIndexPutReq) Reset()                    { *m = RpbYokozunaIndexPutReq{} }
func (m *RpbYokozunaIndexPutReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexPutReq) ProtoMessage()               {}
func (*RpbYokozunaIndexPutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RpbYokozunaIndexPutReq) GetIndex() *RpbYokozunaIndex {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *RpbYokozunaIndexPutReq) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

// DELETE request - Remove an index
type RpbYokozunaIndexDeleteReq struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaIndexDeleteReq) Reset()                    { *m = RpbYokozunaIndexDeleteReq{} }
func (m *RpbYokozunaIndexDeleteReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaIndexDeleteReq) ProtoMessage()               {}
func (*RpbYokozunaIndexDeleteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RpbYokozunaIndexDeleteReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaSchema struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Content          []byte `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaSchema) Reset()                    { *m = RpbYokozunaSchema{} }
func (m *RpbYokozunaSchema) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchema) ProtoMessage()               {}
func (*RpbYokozunaSchema) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RpbYokozunaSchema) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *RpbYokozunaSchema) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// PUT request - create or potentially update a new schema
type RpbYokozunaSchemaPutReq struct {
	Schema           *RpbYokozunaSchema `protobuf:"bytes,1,req,name=schema" json:"schema,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RpbYokozunaSchemaPutReq) Reset()                    { *m = RpbYokozunaSchemaPutReq{} }
func (m *RpbYokozunaSchemaPutReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaPutReq) ProtoMessage()               {}
func (*RpbYokozunaSchemaPutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RpbYokozunaSchemaPutReq) GetSchema() *RpbYokozunaSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

// GET request - Return matching schema by name
type RpbYokozunaSchemaGetReq struct {
	Name             []byte `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RpbYokozunaSchemaGetReq) Reset()                    { *m = RpbYokozunaSchemaGetReq{} }
func (m *RpbYokozunaSchemaGetReq) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaGetReq) ProtoMessage()               {}
func (*RpbYokozunaSchemaGetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RpbYokozunaSchemaGetReq) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type RpbYokozunaSchemaGetResp struct {
	Schema           *RpbYokozunaSchema `protobuf:"bytes,1,req,name=schema" json:"schema,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *RpbYokozunaSchemaGetResp) Reset()                    { *m = RpbYokozunaSchemaGetResp{} }
func (m *RpbYokozunaSchemaGetResp) String() string            { return proto.CompactTextString(m) }
func (*RpbYokozunaSchemaGetResp) ProtoMessage()               {}
func (*RpbYokozunaSchemaGetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RpbYokozunaSchemaGetResp) GetSchema() *RpbYokozunaSchema {
	if m != nil {
		return m.Schema
	}
	return nil
}

func init() {
	proto.RegisterType((*RpbYokozunaIndex)(nil), "RpbYokozunaIndex")
	proto.RegisterType((*RpbYokozunaIndexGetReq)(nil), "RpbYokozunaIndexGetReq")
	proto.RegisterType((*RpbYokozunaIndexGetResp)(nil), "RpbYokozunaIndexGetResp")
	proto.RegisterType((*RpbYokozunaIndexPutReq)(nil), "RpbYokozunaIndexPutReq")
	proto.RegisterType((*RpbYokozunaIndexDeleteReq)(nil), "RpbYokozunaIndexDeleteReq")
	proto.RegisterType((*RpbYokozunaSchema)(nil), "RpbYokozunaSchema")
	proto.RegisterType((*RpbYokozunaSchemaPutReq)(nil), "RpbYokozunaSchemaPutReq")
	proto.RegisterType((*RpbYokozunaSchemaGetReq)(nil), "RpbYokozunaSchemaGetReq")
	proto.RegisterType((*RpbYokozunaSchemaGetResp)(nil), "RpbYokozunaSchemaGetResp")
}

func init() { proto.RegisterFile("riak_yokozuna.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xa5, 0xdd, 0xe6, 0xe0, 0xba, 0x89, 0xcb, 0x60, 0x8b, 0x6f, 0x25, 0x2f, 0x56, 0xd1, 0x0a,
	0xfe, 0x03, 0x8b, 0x1f, 0xf8, 0x36, 0x32, 0x10, 0xc4, 0x87, 0x91, 0xd6, 0x2b, 0x2b, 0x6d, 0x93,
	0xba, 0xa6, 0xa2, 0xfe, 0x7a, 0x59, 0x3f, 0x66, 0xd7, 0x16, 0xc1, 0xb7, 0x9c, 0xe4, 0xdc, 0x73,
	0x73, 0xce, 0xbd, 0x30, 0xdd, 0x04, 0x22, 0x5c, 0x7d, 0xa9, 0x50, 0x7d, 0x67, 0x52, 0x38, 0xc9,
	0x46, 0x69, 0xc5, 0x96, 0x70, 0xcc, 0x13, 0xef, 0xb9, 0xbc, 0x7c, 0x94, 0xaf, 0xf8, 0x49, 0x08,
	0xf4, 0xa5, 0x88, 0x91, 0x1a, 0x96, 0x69, 0x8f, 0x78, 0x7e, 0x26, 0x33, 0x38, 0x48, 0xfd, 0x35,
	0xc6, 0x82, 0x9a, 0x96, 0x61, 0x8f, 0x78, 0x89, 0xc8, 0x14, 0x06, 0x72, 0xf5, 0x21, 0x22, 0xda,
	0xb3, 0x0c, 0x7b, 0xcc, 0xfb, 0xf2, 0x49, 0x44, 0xec, 0x02, 0x66, 0x4d, 0xd1, 0x07, 0xd4, 0x1c,
	0xdf, 0x6b, 0xd2, 0x46, 0x25, 0xcd, 0x5c, 0x98, 0x77, 0xb2, 0xd3, 0x84, 0x9c, 0xc2, 0x20, 0xd8,
	0x62, 0x6a, 0x58, 0x3d, 0xfb, 0xf0, 0x7a, 0xe2, 0x34, 0x89, 0xbc, 0x78, 0x67, 0x2f, 0xed, 0x8e,
	0x8b, 0x2c, 0xef, 0x58, 0x93, 0x30, 0xff, 0x92, 0x20, 0x14, 0x86, 0x3a, 0x88, 0x51, 0x65, 0x3a,
	0xb7, 0x38, 0xe6, 0x15, 0x64, 0x57, 0x70, 0xd2, 0x2c, 0xba, 0xc5, 0x08, 0x35, 0xee, 0x3b, 0xda,
	0x85, 0xc5, 0x6e, 0x60, 0x52, 0x2b, 0x58, 0x16, 0x49, 0x75, 0xa5, 0x4a, 0x61, 0xe8, 0x2b, 0xa9,
	0x51, 0xea, 0x32, 0xd6, 0x0a, 0xb2, 0xbb, 0xbd, 0x50, 0x0a, 0x89, 0xd2, 0xd1, 0xf9, 0x6e, 0x14,
	0x85, 0x25, 0xe2, 0xb4, 0x98, 0xd5, 0x78, 0xd8, 0x65, 0x87, 0x4c, 0x6b, 0x14, 0xbf, 0x1f, 0xbf,
	0x07, 0xda, 0x4d, 0x4f, 0x93, 0xff, 0xb4, 0x75, 0xcf, 0x60, 0xee, 0xab, 0xd8, 0xf1, 0x44, 0xba,
	0x56, 0xce, 0x76, 0xed, 0x8a, 0x6d, 0xf3, 0xb2, 0x37, 0xf7, 0x88, 0x07, 0x22, 0xac, 0xca, 0x16,
	0xee, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x21, 0xdb, 0x32, 0x96, 0x02, 0x00, 0x00,
}
