// Code generated by protoc-gen-go.
// source: riak_search.proto
// DO NOT EDIT!

/*
Package riak_search is a generated protocol buffer package.

It is generated from these files:
	riak_search.proto

It has these top-level messages:
	RpbSearchDoc
	RpbSearchQueryReq
	RpbSearchQueryResp
*/
package riak_search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import riak "github.com/basho/riak-go-client/rpb/riak"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpbSearchDoc struct {
	Fields           []*riak.RpbPair `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RpbSearchDoc) Reset()                    { *m = RpbSearchDoc{} }
func (m *RpbSearchDoc) String() string            { return proto.CompactTextString(m) }
func (*RpbSearchDoc) ProtoMessage()               {}
func (*RpbSearchDoc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpbSearchDoc) GetFields() []*riak.RpbPair {
	if m != nil {
		return m.Fields
	}
	return nil
}

type RpbSearchQueryReq struct {
	Q                []byte   `protobuf:"bytes,1,req,name=q" json:"q,omitempty"`
	Index            []byte   `protobuf:"bytes,2,req,name=index" json:"index,omitempty"`
	Rows             *uint32  `protobuf:"varint,3,opt,name=rows" json:"rows,omitempty"`
	Start            *uint32  `protobuf:"varint,4,opt,name=start" json:"start,omitempty"`
	Sort             []byte   `protobuf:"bytes,5,opt,name=sort" json:"sort,omitempty"`
	Filter           []byte   `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
	Df               []byte   `protobuf:"bytes,7,opt,name=df" json:"df,omitempty"`
	Op               []byte   `protobuf:"bytes,8,opt,name=op" json:"op,omitempty"`
	Fl               [][]byte `protobuf:"bytes,9,rep,name=fl" json:"fl,omitempty"`
	Presort          []byte   `protobuf:"bytes,10,opt,name=presort" json:"presort,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *RpbSearchQueryReq) Reset()                    { *m = RpbSearchQueryReq{} }
func (m *RpbSearchQueryReq) String() string            { return proto.CompactTextString(m) }
func (*RpbSearchQueryReq) ProtoMessage()               {}
func (*RpbSearchQueryReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpbSearchQueryReq) GetQ() []byte {
	if m != nil {
		return m.Q
	}
	return nil
}

func (m *RpbSearchQueryReq) GetIndex() []byte {
	if m != nil {
		return m.Index
	}
	return nil
}

func (m *RpbSearchQueryReq) GetRows() uint32 {
	if m != nil && m.Rows != nil {
		return *m.Rows
	}
	return 0
}

func (m *RpbSearchQueryReq) GetStart() uint32 {
	if m != nil && m.Start != nil {
		return *m.Start
	}
	return 0
}

func (m *RpbSearchQueryReq) GetSort() []byte {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *RpbSearchQueryReq) GetFilter() []byte {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *RpbSearchQueryReq) GetDf() []byte {
	if m != nil {
		return m.Df
	}
	return nil
}

func (m *RpbSearchQueryReq) GetOp() []byte {
	if m != nil {
		return m.Op
	}
	return nil
}

func (m *RpbSearchQueryReq) GetFl() [][]byte {
	if m != nil {
		return m.Fl
	}
	return nil
}

func (m *RpbSearchQueryReq) GetPresort() []byte {
	if m != nil {
		return m.Presort
	}
	return nil
}

type RpbSearchQueryResp struct {
	Docs             []*RpbSearchDoc `protobuf:"bytes,1,rep,name=docs" json:"docs,omitempty"`
	MaxScore         *float32        `protobuf:"fixed32,2,opt,name=max_score,json=maxScore" json:"max_score,omitempty"`
	NumFound         *uint32         `protobuf:"varint,3,opt,name=num_found,json=numFound" json:"num_found,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *RpbSearchQueryResp) Reset()                    { *m = RpbSearchQueryResp{} }
func (m *RpbSearchQueryResp) String() string            { return proto.CompactTextString(m) }
func (*RpbSearchQueryResp) ProtoMessage()               {}
func (*RpbSearchQueryResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpbSearchQueryResp) GetDocs() []*RpbSearchDoc {
	if m != nil {
		return m.Docs
	}
	return nil
}

func (m *RpbSearchQueryResp) GetMaxScore() float32 {
	if m != nil && m.MaxScore != nil {
		return *m.MaxScore
	}
	return 0
}

func (m *RpbSearchQueryResp) GetNumFound() uint32 {
	if m != nil && m.NumFound != nil {
		return *m.NumFound
	}
	return 0
}

func init() {
	proto.RegisterType((*RpbSearchDoc)(nil), "RpbSearchDoc")
	proto.RegisterType((*RpbSearchQueryReq)(nil), "RpbSearchQueryReq")
	proto.RegisterType((*RpbSearchQueryResp)(nil), "RpbSearchQueryResp")
}

func init() { proto.RegisterFile("riak_search.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0xdf, 0x4e, 0x83, 0x30,
	0x14, 0x87, 0x53, 0xf6, 0x8f, 0x1d, 0x99, 0xc9, 0x1a, 0xa3, 0x8d, 0xde, 0xd4, 0xdd, 0xc8, 0x15,
	0x31, 0x3e, 0xc2, 0x62, 0xbc, 0x9e, 0xdd, 0x03, 0x2c, 0x85, 0xb6, 0x19, 0x19, 0xd0, 0xd2, 0x42,
	0x9c, 0x4f, 0xea, 0xeb, 0x98, 0x16, 0xa6, 0xc6, 0xbb, 0xf3, 0x7d, 0xe7, 0x07, 0xed, 0x39, 0x85,
	0xb5, 0x2d, 0xf9, 0xe9, 0xe0, 0x24, 0xb7, 0xc5, 0x31, 0x33, 0x56, 0x77, 0xfa, 0x1e, 0xbc, 0x1a,
	0xea, 0xcd, 0x33, 0x24, 0xcc, 0xe4, 0xfb, 0xd0, 0x7e, 0xd5, 0x05, 0xa6, 0x30, 0x57, 0xa5, 0xac,
	0x84, 0x23, 0x88, 0x4e, 0xd2, 0xab, 0x97, 0x38, 0x63, 0x26, 0xdf, 0xf1, 0xd2, 0xb2, 0xd1, 0x6f,
	0xbe, 0x10, 0xac, 0x7f, 0x3e, 0x79, 0xef, 0xa5, 0xfd, 0x64, 0xb2, 0xc5, 0x09, 0xa0, 0x96, 0x20,
	0x1a, 0xa5, 0x09, 0x43, 0x2d, 0xbe, 0x81, 0x59, 0xd9, 0x08, 0x79, 0x26, 0x51, 0x30, 0x03, 0x60,
	0x0c, 0x53, 0xab, 0x3f, 0x1c, 0x99, 0x50, 0x94, 0xae, 0x58, 0xa8, 0x7d, 0xd2, 0x75, 0xdc, 0x76,
	0x64, 0x1a, 0xe4, 0x00, 0x3e, 0xe9, 0xb4, 0xed, 0xc8, 0x8c, 0xa2, 0x34, 0x61, 0xa1, 0xc6, 0xb7,
	0xfe, 0x66, 0x55, 0x27, 0x2d, 0x99, 0x07, 0x3b, 0x12, 0xbe, 0x86, 0x48, 0x28, 0xb2, 0x08, 0x2e,
	0x12, 0xca, 0xb3, 0x36, 0x24, 0x1e, 0x58, 0x1b, 0xcf, 0xaa, 0x22, 0x4b, 0x3a, 0xf1, 0xac, 0x2a,
	0x4c, 0x60, 0x61, 0xac, 0x0c, 0xbf, 0x87, 0x10, 0xba, 0xe0, 0xa6, 0x05, 0xfc, 0x7f, 0x30, 0x67,
	0xf0, 0x23, 0x4c, 0x85, 0x2e, 0x2e, 0xfb, 0x58, 0x65, 0x7f, 0xd7, 0xc5, 0x42, 0x0b, 0x3f, 0xc0,
	0xb2, 0xe6, 0xe7, 0x83, 0x2b, 0xb4, 0x95, 0x24, 0xa2, 0x28, 0x8d, 0x58, 0x5c, 0xf3, 0xf3, 0xde,
	0xb3, 0x6f, 0x36, 0x7d, 0x7d, 0x50, 0xba, 0x6f, 0xc4, 0x38, 0x7a, 0xdc, 0xf4, 0xf5, 0x9b, 0xe7,
	0xed, 0x13, 0xdc, 0x15, 0xba, 0xce, 0x72, 0xee, 0x8e, 0x3a, 0xfb, 0x7d, 0x96, 0xbc, 0x57, 0xdb,
	0x84, 0x95, 0xfc, 0x34, 0x9c, 0xb4, 0xdb, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x54, 0x27,
	0x7d, 0xc7, 0x01, 0x00, 0x00,
}
